### ISSUE TITLE
add text to "Dołącz do nas" 

### ISSUE THREAD

**Issue by Piegusek07** [CodeForPoznan/codeforpoznan.github.io#6]
text: "Kodujesz? Jesteś grafikiem? UX-owcem? Robisz cokolwiek innego, co może się przydać w kodowaniu dla Poznania? Dołącz do nas! Spotykamy się w każdą środę o godz. 18 przy ul. Morawskiego 12/5 (koło Areny)."

**Comment by w1stler** [comment]
Issue moved to [CodeForPoznan/startbootstrap-freelancer #11](https://github.com/CodeForPoznan/startbootstrap-freelancer/issues/11) via [**ZenHub**](https://www.zenhub.com/)
