### ISSUE TITLE
change name of "Download Theme" button to "Kontakt" in "Dołącz do nas" section 

### ISSUE THREAD

**Issue by Piegusek07** [CodeForPoznan/codeforpoznan.github.io#7]
and add page-scroll option to "Kontakt" section

**Comment by w1stler** [comment]
Issue moved to [CodeForPoznan/startbootstrap-freelancer #10](https://github.com/CodeForPoznan/startbootstrap-freelancer/issues/10) via [**ZenHub**](https://www.zenhub.com/)
